(defproject com.biffweb/biff "0.7.25"
  :description "A full-stack framework for Clojure"
  :url "https://biffweb.com"
  :license {:name "MIT License" :url "https://opensource.org/licenses/MIT"}
  :dependencies [[org.clojure/clojure "1.11.1"]
                 [aero/aero "1.1.6"]
                 [buddy/buddy-sign "3.1.0" :exclusions [cheshire/cheshire com.fasterxml.jackson.core/*]]
                 [cider/cider-nrepl "0.57.0"]
                 [clj-http/clj-http "3.13.1"]
                 [com.nextjournal/beholder "1.0.3"]
                 [com.xtdb/xtdb-core "1.24.5"]
                 [com.xtdb/xtdb-rocksdb "1.24.5"]
                 [com.fasterxml.jackson.core/jackson-core "2.12.7"]
                 [com.fasterxml.jackson.core/jackson-databind "2.12.7.1"]
                 [com.fasterxml.jackson.core/jackson-annotations "2.12.7"]
                 [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.12.7"]
                 [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.12.7"]
                 [com.fasterxml.jackson.datatype/jackson-datatype-jsr310 "2.12.7"]
                 [cheshire/cheshire "5.12.0"]
                 [jarohen/chime "0.3.3"]
                 [lambdaisland/uri "1.19.155"]
                 [metosin/malli "0.19.1"]
                 [metosin/muuntaja "0.6.8" :exclusions [com.fasterxml.jackson.core/*]]
                 [metosin/reitit-ring "0.5.18"]
                 [nrepl/nrepl "1.4.0"]
                 [org.clojure/tools.logging "1.3.0"]
                 [org.clojure/tools.namespace "1.5.0"]
                 [org.eclipse.jetty/jetty-server "9.4.52.v20230823"]
                 [org.eclipse.jetty/jetty-servlet "9.4.52.v20230823"]
                 [org.eclipse.jetty/jetty-webapp "9.4.52.v20230823"]
                 [org.eclipse.jetty/jetty-util "9.4.52.v20230823"]
                 [org.eclipse.jetty/jetty-http "9.4.52.v20230823"]
                 [org.eclipse.jetty/jetty-io "9.4.52.v20230823"]
                 [org.postgresql/postgresql "42.2.24"]
                 [org.slf4j/slf4j-api "1.7.36"]
                 [refactor-nrepl/refactor-nrepl "3.11.0"]
                 [ring/ring-core "1.9.6"]
                 [ring/ring-defaults "0.3.3"]
                 [ring/ring-jetty-adapter "1.10.0"]
                 [rum/rum "0.12.11"]]
  :exclusions [[org.eclipse.jetty/*] [com.fasterxml.jackson.core/*] [com.fasterxml.jackson.dataformat/*]]
  :plugins [[lein-cljfmt "0.8.2"]]
  :source-paths ["src" "libs/config/src"]
  :test-paths ["test"]
  :javac-options ["-target" "1.8" "-source" "1.8"]
  :main ^:skip-aot com.biffweb
  :profiles {:dev {:dependencies [[org.slf4j/slf4j-simple "1.7.36"]]
                   :main-opts ["-m" "nrepl.cmdline"]}})